added prisma shortcut to root

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -5,17 +5,17 @@ fileList=$(git diff --cached --name-only :^README.md :^LISEZ-MOI.md :^frontend :
 
 echo '----- Checking Root...'
 
-# if [ ! -z "$fileList" ]
-# then
-#   echo "error: Unauthorized modifications\n"
+if [ ! -z "$fileList" ]
+then
+  echo "error: Unauthorized modifications\n"
 
-#   echo "$fileList\n"
+  echo "$fileList\n"
 
-#   echo "use 'git restore ...' to fix the problem"
-#   echo "(and ask your instructor why you should not change these files)\n"
+  echo "use 'git restore ...' to fix the problem"
+  echo "(and ask your instructor why you should not change these files)\n"
 
-#   exit 1
-# fi
+  exit 1
+fi
 
 echo '----- Done!'
 
